/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.VIEW.TogetherSERVICE;

import jakarta.persistence.JoinColumn;
import org.example.ENTITY.Computer.Computer;
import org.example.ENTITY.Computer.Status;
import org.example.ENTITY.USER.User;
import org.example.SERVICE.ComputerService;
import org.example.SERVICE.UserService;
import org.example.VIEW.USER.HomeUserJFrame;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author HELLO MAIN_CA
 */
public class ComputerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ComputerJFrame
     */
    public ComputerJFrame() {
        initComponents();
    }
    public ComputerJFrame(String phone) {
        initComponents();
        PhonNowTXT.setText(phone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PhonNowTXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableComuper = new javax.swing.JTable();
        OpentComputerButton = new javax.swing.JButton();
        RefreshComputer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Computer_ID_TXT = new javax.swing.JTextField();
        ExitComputerDailogButton = new javax.swing.JButton();

        PhonNowTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 650));

        TableComuper.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TableComuper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Máy", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableComuper.setRowHeight(50);
        TableComuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableComuperMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableComuper);

        OpentComputerButton.setBackground(new java.awt.Color(204, 255, 255));
        OpentComputerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OpentComputerButton.setText("Mở máy");
        OpentComputerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpentComputerButtonActionPerformed(evt);
            }
        });

        RefreshComputer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RefreshComputer.setForeground(new java.awt.Color(0, 153, 51));
        RefreshComputer.setText("Làm mới máy");
        RefreshComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshComputerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tên máy");

        Computer_ID_TXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ExitComputerDailogButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitComputerDailogButton.setText("Hủy");
        ExitComputerDailogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitComputerDailogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Computer_ID_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addComponent(OpentComputerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RefreshComputer, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(ExitComputerDailogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Computer_ID_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OpentComputerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(ExitComputerDailogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableComuperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableComuperMouseClicked
        // TODO add your handling code here:
        int selectedRow = TableComuper.getSelectedRow(); // Lấy hàng đang được chọn
        if (selectedRow != -1) {
            String col1 = TableComuper.getValueAt(selectedRow, 0).toString();
            Computer_ID_TXT.setText(col1);
        }
    }//GEN-LAST:event_TableComuperMouseClicked

    private void RefreshComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshComputerActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableComuper.getModel();
        model.setRowCount(0); // Xóa toàn bộ dữ liệu nhưng giữ lại các cột
        ComputerService computerService = new ComputerService();
        ArrayList<Computer> computers = computerService.selectAllComputer();
        for(Computer computer : computers){
            model.addRow(new Object[]{computer.getName(), computer.getStatus().getDescription()});
        }
        JOptionPane.showMessageDialog(this,"Đã làm mới", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RefreshComputerActionPerformed

    private void OpentComputerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpentComputerButtonActionPerformed
        // TODO add your handling code here:
        UserService userService = new UserService();
        ComputerService computerService = new ComputerService();
        Computer computer = computerService.findComputer(Computer_ID_TXT.getText());
        if(computer == null){
            JOptionPane.showMessageDialog(this,"Hãy chọn máy",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        User user = userService.findUser(PhonNowTXT.getText());
        if(computer.getUser() != null || computer.getStatus().equals(Status.IN_USE)) {
            JOptionPane.showMessageDialog(this,"Máy đang được sử dụng",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logoTichXanh.png"));
        JOptionPane.showMessageDialog(this,"Đăng nhập thành công",
                "Thông báo",JOptionPane.INFORMATION_MESSAGE, icon);
        computer.setUser(user);
        computer.setStatus(Status.IN_USE);
        computerService.addComputer(computer);
        this.setVisible(false);
        new HomeUserJFrame(PhonNowTXT.getText()).setVisible(true);
    }//GEN-LAST:event_OpentComputerButtonActionPerformed

    private void ExitComputerDailogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitComputerDailogButtonActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this,"Xác nhận hủy",
                "Thông báo",JOptionPane.OK_OPTION);
        if(check == JOptionPane.OK_OPTION)
            this.setVisible(false);
        new HomeJFrame().setVisible(true);
    }//GEN-LAST:event_ExitComputerDailogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Computer_ID_TXT;
    private javax.swing.JButton ExitComputerDailogButton;
    private javax.swing.JButton OpentComputerButton;
    private javax.swing.JTextField PhonNowTXT;
    private javax.swing.JButton RefreshComputer;
    private javax.swing.JTable TableComuper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
