/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.VIEW.TogetherSERVICE;

import org.example.ENTITY.USER.User;
import org.mindrot.jbcrypt.BCrypt;

import javax.swing.*;

import java.util.Arrays;
import java.util.Random;

import static org.example.DAO.Main.entityManager;

/**
 *
 * @author HELLO MAIN_CA
 */
public class ForgotPassJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassJFrame
     */
    public ForgotPassJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewPassDailog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        PassJpane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        YesNewPAssButton = new javax.swing.JButton();
        ExitNewPassButton = new javax.swing.JButton();
        PassTXT = new javax.swing.JPasswordField();
        ACPassTXT = new javax.swing.JPasswordField();
        GiveOTP = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        OTP_Txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        PhoneCheckNewPassTXT = new javax.swing.JTextField();
        CheckPhoneNewPassButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        OTP_TXT = new javax.swing.JTextField();
        YesCheckPhoneNewPassButton = new javax.swing.JButton();
        ExitCheckPhoneNewPassButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        NewPassDailog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        NewPassDailog.setModal(true);
        NewPassDailog.setResizable(false);
        NewPassDailog.setSize(new java.awt.Dimension(500, 230));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("TẠO MẬT KHẨU MỚI");

        PassJpane.setBackground(new java.awt.Color(241, 254, 254));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nhập mật khẩu mới");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Xác nhận mật khẩu");

        YesNewPAssButton.setText("Hoàn tất");
        YesNewPAssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesNewPAssButtonActionPerformed(evt);
            }
        });

        ExitNewPassButton.setText("Hủy");
        ExitNewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitNewPassButtonActionPerformed(evt);
            }
        });

        PassTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ACPassTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout PassJpaneLayout = new javax.swing.GroupLayout(PassJpane);
        PassJpane.setLayout(PassJpaneLayout);
        PassJpaneLayout.setHorizontalGroup(
            PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassJpaneLayout.createSequentialGroup()
                .addGroup(PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PassJpaneLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ACPassTXT))
                    .addGroup(PassJpaneLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(YesNewPAssButton)
                        .addGap(33, 33, 33)
                        .addComponent(ExitNewPassButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PassJpaneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassTXT)))
                .addContainerGap())
        );
        PassJpaneLayout.setVerticalGroup(
            PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassJpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PassTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ACPassTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PassJpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitNewPassButton)
                    .addComponent(YesNewPAssButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewPassDailogLayout = new javax.swing.GroupLayout(NewPassDailog.getContentPane());
        NewPassDailog.getContentPane().setLayout(NewPassDailogLayout);
        NewPassDailogLayout.setHorizontalGroup(
            NewPassDailogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPassDailogLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(NewPassDailogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PassJpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewPassDailogLayout.setVerticalGroup(
            NewPassDailogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPassDailogLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassJpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        GiveOTP.setResizable(false);
        GiveOTP.setSize(new java.awt.Dimension(240, 140));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Mã OTP của bạn là");

        OTP_Txt.setEditable(false);
        OTP_Txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OTP_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTP_TxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GiveOTPLayout = new javax.swing.GroupLayout(GiveOTP.getContentPane());
        GiveOTP.getContentPane().setLayout(GiveOTPLayout);
        GiveOTPLayout.setHorizontalGroup(
            GiveOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiveOTPLayout.createSequentialGroup()
                .addGroup(GiveOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GiveOTPLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(OTP_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GiveOTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        GiveOTPLayout.setVerticalGroup(
            GiveOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiveOTPLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(OTP_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lây lại mật khẩu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 254, 254));

        PhoneCheckNewPassTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CheckPhoneNewPassButton.setText("Nhận mã");
        CheckPhoneNewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPhoneNewPassButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("OTP");

        OTP_TXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        YesCheckPhoneNewPassButton.setText("Hoàn tất");
        YesCheckPhoneNewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCheckPhoneNewPassButtonActionPerformed(evt);
            }
        });

        ExitCheckPhoneNewPassButton.setText("Hủy");
        ExitCheckPhoneNewPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitCheckPhoneNewPassButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Số điện thoại");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setText("Nhập mã OTP đã được gửi đến số điện thoại của bạn.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckPhoneNewPassButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(YesCheckPhoneNewPassButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExitCheckPhoneNewPassButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneCheckNewPassTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OTP_TXT))
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneCheckNewPassTXT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckPhoneNewPassButton)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OTP_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesCheckPhoneNewPassButton)
                    .addComponent(ExitCheckPhoneNewPassButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("XÁC NHẬN DANH TÍNH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesCheckPhoneNewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCheckPhoneNewPassButtonActionPerformed
        // TODO add your handling code here:
        if(!OTP_TXT.getText().equals(OTP_Txt.getText())) {
            JOptionPane.showMessageDialog(this, "Mã OTP không chính xác",
                    "Thông báo", JOptionPane.OK_OPTION);
            return;
        }
        NewPassDailog.setVisible(true);
    }//GEN-LAST:event_YesCheckPhoneNewPassButtonActionPerformed

    private void ExitCheckPhoneNewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitCheckPhoneNewPassButtonActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "XÁC NHẬN HỦY!",
                "THÔNG BÁO", JOptionPane.INFORMATION_MESSAGE);
        if(check == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new HomeJFrame().setVisible(true);
        }

    }//GEN-LAST:event_ExitCheckPhoneNewPassButtonActionPerformed

    private void ExitNewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitNewPassButtonActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this,"XÁC NHẬN HỦY!",
                "Thông báo",JOptionPane.INFORMATION_MESSAGE);
        if(check == JOptionPane.OK_OPTION){
            NewPassDailog.setVisible(false);
        }
    }//GEN-LAST:event_ExitNewPassButtonActionPerformed

    private void YesNewPAssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesNewPAssButtonActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this,"Xác nhận thay đổi",
                "Thông báo",JOptionPane.INFORMATION_MESSAGE);
        if(check == JOptionPane.OK_OPTION){
            this.setVisible(false);
            NewPassDailog.setVisible(false);
            GiveOTP.setVisible(false);
            new HomeJFrame().setVisible(true);
            User user = entityManager.find(User.class,PhoneCheckNewPassTXT.getText());
            char[] passChar = ACPassTXT.getPassword();
            String pass = BCrypt.hashpw(String.valueOf(passChar), BCrypt.gensalt());
            user.setPassword(pass);
            pass = "";
            Arrays.fill(passChar,'\0');
            entityManager.getTransaction().begin();
            entityManager.merge(user);
            entityManager.getTransaction().commit();
        }
    }//GEN-LAST:event_YesNewPAssButtonActionPerformed

    private void CheckPhoneNewPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPhoneNewPassButtonActionPerformed
        // TODO add your handling code here:
        User user = entityManager.find(User.class,PhoneCheckNewPassTXT.getText());
        if(user == null){
            JOptionPane.showMessageDialog(this,"Tài khoản không tồn tại",
                    "Thông báo",JOptionPane.OK_OPTION);
            return;
        }
        Random random = new Random();
        int otp = random.nextInt(9000);
        String OTP = String.valueOf(otp);
        while(OTP.length()<4)
            OTP = '0' + OTP;
        OTP_Txt.setText(OTP);
        GiveOTP.setVisible(true);
    }//GEN-LAST:event_CheckPhoneNewPassButtonActionPerformed

    private void OTP_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTP_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTP_TxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ACPassTXT;
    private javax.swing.JButton CheckPhoneNewPassButton;
    private javax.swing.JButton ExitCheckPhoneNewPassButton;
    private javax.swing.JButton ExitNewPassButton;
    private javax.swing.JDialog GiveOTP;
    private javax.swing.JDialog NewPassDailog;
    private javax.swing.JTextField OTP_TXT;
    private javax.swing.JTextField OTP_Txt;
    private javax.swing.JPanel PassJpane;
    private javax.swing.JPasswordField PassTXT;
    private javax.swing.JTextField PhoneCheckNewPassTXT;
    private javax.swing.JButton YesCheckPhoneNewPassButton;
    private javax.swing.JButton YesNewPAssButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
