/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.VIEW.TogetherSERVICE;

import java.awt.event.ActionEvent;
import java.lang.reflect.Array;
import java.util.Arrays;

import org.example.ENTYTI.USER.Role;
import org.mindrot.jbcrypt.BCrypt;
import org.example.ENTYTI.USER.User;
import org.example.VIEW.BOSS.HomeBossJFrame;
import org.example.VIEW.USER.HomeUserJFrame;

import javax.swing.*;

import static javax.swing.JOptionPane.showMessageDialog;
import static org.example.DAO.Main.entityManager;

/**
 *
 * @author HELLO MAIN_CA
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        QuenMatKhauButton = new javax.swing.JToggleButton();
        UserNameTxt = new javax.swing.JTextField();
        PasswordTXT = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText(" CÔNG TY GIẢI TRÍ VÀ DỊCH VỤ THỂ THAO ĐIỆN TỬ ADC VÙNG CAO");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField2.setText("                            QUÁN NET ADC VÙNG CAO – NƠI GAME THỦ TỎA SÁNG! ");

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText(">>> 1. Giới thiệu chung <<<\n         Chào mừng bạn đến với ABS Vùng Cao – thiên đường giải trí dành cho game thủ! Với hệ thống máy cấu hình siêu khủng, đường truyền siêu tốc và không gian thoải mái – chuyên nghiệp, chúng tôi mang đến trải nghiệm gaming đỉnh cao cho mọi khách hàng.\n\n>>> 2. Cơ sở vật chất & dịch vụ <<<\n         [v] Dàn máy cấu hình cao – Chiến mọi tựa game từ FPS đến MOBA!\n         [v] Ghế gaming êm ái – Ngồi lâu vẫn thoải mái, không đau lưng.\n         [v] Mạng Internet tốc độ cao – Không lo lag, ping cực thấp!\n         [v] Không gian rộng rãi, mát mẻ – Thiết kế hiện đại, có khu vực nghỉ ngơi.\n         [v] Đồ ăn & nước uống đa dạng – Sẵn sàng tiếp năng lượng cho game thủ.\n         [v] Nhân viên hỗ trợ tận tình – Luôn sẵn sàng giúp đỡ bạn.\n\n>>> 3. Ưu đãi hấp dẫn <<<\n         [v] Khuyến mãi giờ chơi – Nạp càng nhiều, thưởng càng lớn!\n         [v] Giải đấu eSports định kỳ – So tài cùng những game thủ xuất sắc.\n         [v] Thành viên VIP – Giảm giá đặc biệt, ưu đãi cực hot!\n\n>>> Thông tin liên hệ <<<\n         Địa chỉ: Một nơi trên Server Này\n         Liên hệ: 0323 232 323\n\n\n\n\n=============================================================================================\n                                                        Hãy đến ABS Vùng Cao và chinh phục mọi trận đấu ngay hôm nay!\n=============================================================================================");
        jTextArea5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trang chủ", jPanel1);

        jTextField3.setEditable(false);
        jTextField3.setBackground(java.awt.SystemColor.control);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTextField3.setText("                                        DỊCH VỤ TẠI QUÁN NET ABS VÙNG CAO ");

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("1. Dịch vụ máy tính & gaming\n\tMáy tính cấu hình cao – Chiến game mượt mà, FPS ổn định.\n\tGhế gaming êm ái – Ngồi lâu không đau lưng, thoải mái cày game.\n\tMạng Internet tốc độ cao – Ping thấp, không lo giật lag.\n\tHỗ trợ cài đặt game & phần mềm – Đáp ứng mọi nhu cầu của khách hàng.\n\tHệ thống tài khoản thành viên – Tiết kiệm chi phí, tích điểm nhận thưởng.\n\n2. Dịch vụ ăn uống tại chỗ\n\tMenu đa dạng – Mì cay, cơm văn phòng, snack, nước ngọt, cà phê...\n\tPhục vụ tận nơi – Gọi món ngay tại máy, không gián đoạn cuộc chơi.\n\tCombo game thủ – Tiết kiệm chi phí, no bụng mà vẫn tập trung chiến đấu.\n\n3. Dịch vụ tổ chức giải đấu & sự kiện\n\tGiải đấu eSports – Dành cho các team và game thủ đam mê thi đấu.\n\tOffline giao lưu game thủ – Tạo cơ hội kết nối cộng đồng gaming.\n\tLive stream & bình luận trực tiếp – Hỗ trợ streamer, caster.\n\n4. Dịch vụ hỗ trợ kỹ thuật\n\tSửa chữa, nâng cấp PC – Hỗ trợ nâng cấp phần cứng, vệ sinh máy.\n\tCài đặt game theo yêu cầu – Đáp ứng mọi tựa game HOT nhất.\n\tHỗ trợ khách hàng 24/7 – Nhân viên luôn sẵn sàng giúp đỡ.\n\n5. Dịch vụ tài khoản & nạp thẻ\n\tNạp thẻ game – Liên Minh, PUBG, Valorant, Steam, Mobile Legends…\n\tBán tài khoản VIP – Game, Netflix, Spotify, ChatGPT Plus...\n\tĐổi thưởng – Giftcode – Quà tặng hấp dẫn cho khách hàng thân thiết.\n\nABS Vùng Cao – Hơn cả một quán net, là nơi kết nối đam mê eSports!");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dịch vụ", jPanel2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo the thao.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mật khẩu");

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 51, 204));
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconLogo.png"))); // NOI18N
        LoginButton.setText("Đăng nhập");
        LoginButton.setMaximumSize(new java.awt.Dimension(50, 50));
        LoginButton.setMinimumSize(new java.awt.Dimension(50, 50));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tài khoản");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Nhập thông tin đăng nhập");

        QuenMatKhauButton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        QuenMatKhauButton.setForeground(new java.awt.Color(255, 0, 51));
        QuenMatKhauButton.setText("Quên mật khẩu ?");
        QuenMatKhauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuenMatKhauButtonActionPerformed(evt);
            }
        });

        UserNameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PasswordTXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QuenMatKhauButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addComponent(PasswordTXT)
                            .addComponent(UserNameTxt))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PasswordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(QuenMatKhauButton)
                .addGap(82, 82, 82)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTXTActionPerformed(ActionEvent evt) {
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void QuenMatKhauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuenMatKhauButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ForgotPassJFrame().setVisible(true);
    }//GEN-LAST:event_QuenMatKhauButtonActionPerformed


    //LOGIN==============================================================================================================
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String phone = UserNameTxt.getText();
        if(UserNameTxt.getText().isBlank() || String.valueOf(PasswordTXT.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(this,"Không để trống thông tin",
                    "Thông báo",JOptionPane.OK_OPTION);
            return;
        }

        User user = entityManager.find(User.class, phone);
        if(user == null){
            JOptionPane.showMessageDialog(this,"Tài khoản không tồn tại !",
                    "Thông báo",JOptionPane.OK_OPTION);
            return;
        }
        char[] passwordChar = PasswordTXT.getPassword();
        if(!BCrypt.checkpw(String.valueOf(passwordChar), user.getPassword())){
            JOptionPane.showMessageDialog(this,"Mật khẩu không chính xác !",
                    "Thông báo",JOptionPane.OK_OPTION);
            return;
        }
        Arrays.fill(passwordChar,'\0');
        if(user.getRole() == Role.ADMIN){
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/logoTichXanh.png"));
            JOptionPane.showMessageDialog(this,"Xin Chào ADMIN",
                    "Thông báo",JOptionPane.INFORMATION_MESSAGE, icon);
            this.setVisible(false);
            new HomeBossJFrame().setVisible(true);
            return;
        }
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logoTichXanh.png"));
        JOptionPane.showMessageDialog(this,"Đăng nhập thành công",
                "Thông báo",JOptionPane.INFORMATION_MESSAGE, icon);
        this.setVisible(false);
        new HomeUserJFrame(phone).setVisible(true);

    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton LoginButton;
    private javax.swing.JPasswordField PasswordTXT;
    private javax.swing.JToggleButton QuenMatKhauButton;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
